### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Kesonjus** [25web/climatechange#4]
voi tulla muutoksia sen takia pidetään issue auki

**Comment by tomlnd** [comment]
The database returns the following error
```sql
code: 'UNKNOWN_CODE_PLEASE_REPORT',
errno: 4025,
sqlMessage: 'CONSTRAINT `views.charts` failed for `webdb`.`views`',
sqlState: '23000',
index: 0,
sql: "INSERT INTO views (url, charts, user_ID) VALUES ('XmxLB-CGM','v1,v2',7)"
```
when trying to save a new custom view into the DB.
https://github.com/25web/climatechange/blob/c544d028e477627c15a526d084c7380464b81e5d/backend/models/viewModel.js#L8-L14
